# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# PE 2016.4.15  4.10     2.1.9  2018-12 (LTS)
# SIMP 6.1      4.10     2.1.9  TBD
# SIMP 6.2      4.10     2.1.9  TBD
# SIMP 6.3      5.5      2.4.4  TBD***
# PE 2018.1     5.5.6    2.4.4  2020-05 (LTS)***
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
stages:
  - 'sanity'
  - 'validation'
  - 'acceptance'
  - 'compliance'
  - 'deployment'

image: 'ruby:2.1'

variables:
  PUPPET_VERSION:    'UNDEFINED' # <- Matrixed jobs MUST override this (or fail)
  BUNDLER_VERSION:   '1.16.1'

  # Force dependencies into a path the gitlab-runner user can write to.
  # (This avoids some failures on Runners with misconfigured ruby environments.)
  GEM_HOME:          .vendor/gem_install
  BUNDLE_CACHE_PATH: .vendor/bundle
  BUNDLE_PATH:       .vendor/bundle
  BUNDLE_BIN:        .vendor/gem_install/bin
  BUNDLE_NO_PRUNE:   'true'


# bundler dependencies and caching
#
# - Cache bundler gems between pipelines foreach Ruby version
# - Try to use cached and local resources before downloading dependencies
# --------------------------------------
.setup_bundler_env: &setup_bundler_env
  cache:
    untracked: true
    key: "${CI_PROJECT_NAMESPACE}_ruby-${MATRIX_RUBY_VERSION}_bundler"
    paths:
      - '.vendor'
  before_script:
    - 'ruby -e "puts %(Environment Variables:\n  * #{ENV.keys.grep(/PUPPET|SIMP|BEAKER|MATRIX/).map{|v| %(#{v} = #{ENV[v]})}.join(%(\n  * ))})"'
    - 'declare GEM_BUNDLER_VER=(-v "~> ${BUNDLER_VERSION:-1.16.0}")'
    - 'declare GEM_INSTALL_CMD=(gem install --no-document)'
    - 'declare BUNDLER_INSTALL_CMD=(bundle install --no-binstubs --jobs $(nproc) "${FLAGS[@]}")'
    - 'mkdir -p ${GEM_HOME} ${BUNDLER_BIN}'
    - 'gem list -ie "${GEM_BUNDLER_VER[@]}" --silent bundler || "${GEM_INSTALL_CMD[@]}" --local "${GEM_BUNDLER_VER[@]}" bundler || "${GEM_INSTALL_CMD[@]}" "${GEM_BUNDLER_VER[@]}" bundler'
    - 'rm -rf pkg/ || :'
    - 'bundle check || rm -f Gemfile.lock && ("${BUNDLER_INSTALL_CMD[@]}" --local || "${BUNDLER_INSTALL_CMD[@]}" || bundle pristine ||  "${BUNDLER_INSTALL_CMD[@]}") || echo "PIPELNE: Bundler could not find everything"'

# To avoid running a prohibitive number of tests every commit,
# don't set this env var in your gitlab instance
.only_with_SIMP_FULL_MATRIX: &only_with_SIMP_FULL_MATRIX
  only:
    variables:
      - $SIMP_FULL_MATRIX

# Puppet + testing environments
# --------------------------------------
.pup_prev: &pup_prev
  image: 'ruby:2.1'
  variables:
    PUPPET_VERSION: '~> 4.10.4'
    MATRIX_RUBY_VERSION: '2.1'

# PE 2018.1
.pe_current: &pe_current
  image: 'ruby:2.4'
  variables:
    PUPPET_VERSION: '5.5.6'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    MATRIX_RUBY_VERSION: '2.4'

# Puppet for 6.3
.pup_current: &pup_current
  image: 'ruby:2.4'
  variables:
    PUPPET_VERSION: '~> 5.5.7'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    MATRIX_RUBY_VERSION: '2.4'

.pup_latest: &pup_latest
  image: 'ruby:2.4'
  variables:
    PUPPET_VERSION: '~> 5.0'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    MATRIX_RUBY_VERSION: '2.4'


.lint_tests: &lint_tests
  stage: 'validation'
  tags: ['docker']
  <<: *setup_bundler_env
  script:
    - 'bundle exec rake syntax'
    - 'bundle exec rake lint'

.unit_tests: &unit_tests
  stage: 'validation'
  tags: ['docker']
  <<: *setup_bundler_env
  script:
    - 'bundle exec rake spec'

.acceptance_base: &acceptance_base
  stage: 'acceptance'
  tags: ['beaker']
  <<: *setup_bundler_env

.compliance_base: &compliance_base
  stage: 'compliance'
  tags: ['beaker']
  <<: *setup_bundler_env


# Pipeline / testing matrix
#=======================================================================

sanity_checks:
  <<: *pup_latest
  <<: *setup_bundler_env
  stage: 'sanity'
  tags: ['docker']
  script:
    - 'bundle exec rake check:dot_underscore'
    - 'bundle exec rake check:test_file'
    - 'bundle exec rake pkg:check_version'
    - 'bundle exec rake pkg:compare_latest_tag'


pup-prev-lint:
  <<: *pup_prev
  <<: *lint_tests

pup-current-lint:
  <<: *pup_current
  <<: *lint_tests

pup-latest-lint:
  <<: *pup_latest
  <<: *lint_tests


pup-prev-unit:
  <<: *pup_prev
  <<: *unit_tests

pe-current-unit:
  <<: *pe_current
  <<: *unit_tests

pup-current-unit:
  <<: *pup_current
  <<: *unit_tests

pup-latest-unit:
  <<: *pup_latest
  <<: *unit_tests


#pup-prev-default:
#  <<: *pup_prev
#  <<: *acceptance_base
#  script:
#    - 'bundle exec rake beaker:suites'
#
#pup-prev-fips-default:
#  <<: *pup_prev
#  <<: *acceptance_base
#  <<: *only_with_SIMP_FULL_MATRIX
#  script:
#    - 'BEAKER_fips=yes bundle exec rake beaker:suites'
#
#pup-current-default:
#  <<: *pup_current
#  <<: *acceptance_base
#  script:
#    - 'bundle exec rake beaker:suites'
#
#pup-current-fips-default:
#  <<: *pup_current
#  <<: *acceptance_base
#  script:
#    - 'BEAKER_fips=yes bundle exec rake beaker:suites'
#
#pup-current-oel-default:
#  <<: *pup_current
#  <<: *acceptance_base
#  script:
#    - 'bundle exec rake beaker:suites[default,oel]'
#
#pup-current-oel-fips-default:
#  <<: *pup_current
#  <<: *acceptance_base
#  <<: *only_with_SIMP_FULL_MATRIX
#  script:
#    - 'BEAKER_fips=yes bundle exec rake beaker:suites[default,oel]'
#
# FUTURE
#pup-current-fips-compliance:
#  <<: *pup_current
#  <<: *compliance_base
#  script:
#    - 'BEAKER_fips=yes bundle exec rake beaker:suites[compliance]'
#
## Deployment jobs
##=======================================================================
#
#module_build:
#  only:
#    - 'tags'
#  stage: 'deployment'
#  tags:
#    - 'docker'
#  script:
#    - 'bundle exec rake clean'
#    - 'rm -rf pkg/'
#    - 'bundle exec puppet module build'
#  artifacts:
#    name: 'forge_release-${CI_COMMIT_TAG}'
#    when: 'on_success'
#    paths:
#      - 'pkg/${MODULE_NAME}-${MODULE_VERSION}.tar.gz'

# vi:tabstop=2:shiftwidth=2:expandtab
